### ISSUE TITLE
Zoom window doesn't handle rotation properly

### ISSUE THREAD

**Issue by nicked** [myell0w/MTZoomWindow#2]
I have an app that can rotate to any orientation on the iPad. Sometimes when I zoom in on a view, the zoomed view comes up sideways. It seems to depend on how the iPad was orientated when I started up the app.

Also, when the iPad is rotated while the zoomed in view is visible, the zoomed image shrinks to a tiny square in the corner of the black screen - its the same as the zoomed out size.

**Comment by myell0w** [comment]
There is a simple workaround for this issue: Create the instance of MTZoomWindow in your applicationDidFinishLaunchingWithOptions: method by just calling [MTZoomWindow sharedWindow] there. That way the window get's initialized and updates the rotation properly.

**Comment by nicked** [comment]
Thanks, that fixes the "wrong starting orientation" problem (I missed that bit in the readme somehow!).

However, there is still the problem that when you rotate while the view is zoomed in, it reverts to the original smaller size.

Would it be caused by this line in `orientationWillChange`?
`[self.scrollView setZoomScale:1.f animated:YES];`

**Comment by myell0w** [comment]
No worries. Yes, that's caused by this line and was an easy workaround for some problems I encountered otherwise. Feel free to improve on the behavior and send me a pull request!

Am 14.10.2012 um 02:40 schrieb nicked notifications@github.com:
